version: '2'

services:
  web:
    image: nginx:latest
    restart: always
    ports:
      - "80:80"
    volumes:
      - ../:/var/www/
      - ../public:/var/www/public
      - ./log/nginx:/var/log/nginx
      - ./conf/nginx/conf.d:/etc/nginx/conf.d/
      - ./conf/nginx/nginx.conf:/etc/nginx/nginx.conf
    links:
      - php
  php:
    image: phalconphp/php-fpm:7
    restart: always
    volumes:
      - ../:/var/www/
      - ../public:/var/www/public

  mysql:
    image: mysql:5.7
    restart: always
    expose:
      - "3306"
    ports:
      - "3306:3306"
    volumes:
      - ./data/mysql:/var/lib/mysql
    env_file:
      - env.conf
      
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:4.6
    restart: always
    depends_on:
      - mysql
    ports:
      - "8080:80"
    env_file:
      - env.conf

  mongo:
    image: mongo:3.4
    restart: always
    expose:
      - "27017"
    ports:
      - "27017:27017"
    #volumes:
      #- ./data/mongodb:/data/db
      
  redis:
    image: redis:3.2
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - ./data/redis:/data
      - ./conf/redis/redis.conf:/etc/redis/redis.conf
      
  memcached:
    image: memcached:1.4
    restart: always
    ports:
      - "11211:11211"

#sed -i 's/archive.ubuntu.com/mirror.ehost.vn/g' /etc/apt/sources.list
#docker cp id_or_name:/nginx/conf.d /docker/nginx-php/nginx/
#docker exec -t -i id_or_name /bin/bash